version: '2'

services:
    nginx:
        image: nginx:1.21.6
        ports:
            - "80:80"
            #- "443:443"
        volumes:
            - ./conf/nginx:/etc/nginx/conf.d
            - ./..:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - php
        environment:
            TZ: Europe/Moscow
        networks:
            - ${COMPOSE_PROJECT_NAME}
    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php
        build: ./conf/php
        volumes:
            - ./..:/var/www
            - ~/.ssh:/root/.ssh
            - ./conf/php/hosts_default:/etc/hosts_default:ro
            - ./conf/php/hosts:/etc/hosts
            - ./conf/php/start.sh:/start.sh
            - ./conf/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
            - ./logs/php:/var/log/php
        command: >
            bash -c "
            chmod u+x  /start.sh
            && /start.sh"
        environment:
            TZ: Europe/Moscow
        user: "www-data:www-data"
        networks:
            - ${COMPOSE_PROJECT_NAME}
        extra_hosts:
            - host.docker.internal:host-gateway

networks:
    konkord:
        driver: bridge